services:
  mysql:
    image: mysql
    # Don't use mysl_native_password like we do here
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=SecretPass
      - MYSQL_DATABASE=root
    ports:
      - 3306:3306
    volumes:
      - ./.database:/var/lib/mysql
